export const projects = [
  {
    title: "NextBnB",
    description:
      "NextBnB is a platform that connects hosts who have accommodations to rent with guests seeking to rent such accommodations. The platform is a two-sided marketplace that allows hosts to list their accommodations and guests to book them.",
    src: "/projects/nextbnb/next1.png",
    link: "https://nextbnb-dusky.vercel.app//",
    color: "#FF6202",
    text: "#000000",
    type: "Personal Project",
    techStack: [
      "Next.js",
      "Tailwind CSS",
      "MongoDB",
      "Typesctipt",
      "Prisma",
      "next-auth",
    ],
    images: [
      "/projects/nextbnb/next1.png",
      "/projects/nextbnb/next2.png",
      "/projects/nextbnb/next3.png",
      "/projects/nextbnb/next4.png",
    ],
  },
  {
    title: "Skillbrisk - Freelancing Platform",

    description:
      "Skillbrisk is a platform that connects freelancers with clients. The platform allows freelancers to create profiles, list their skills, and apply for jobs. Clients can post jobs, view freelancer profiles, and hire freelancers.",
    src: "/projects/skillbrisk/sb1.png",
    type: "Personal Project",
    techStack: [
      "Reactjs, Nodejs, Expressjs",
      "Nextjs",
      "Tailwind CSS",
      "MongoDB",
      "Stripe",
      "Redux",
    ],
    link: "https://www.ignant.com/2022/09/30/clement-chapillon-questions-geographical-and-mental-isolation-with-les-rochers-fauves/",
    color: "#1e35ff",
    text: "#FFFFFF",
    images: [
      "/projects/skillbrisk/sb1.png",
      "/projects/skillbrisk/sb2.png",
      "/projects/skillbrisk/sb3.png",
      "/projects/skillbrisk/sb4.png",
    ],
  },
  {
    title: "Eternart - E-commerce Platform",
    description:
      "An e-commerce platform that allows users to browse products, add them to their cart, and purchase them. The platform also allows users to create accounts, view their order history, and manage their account settings.",
    src: "/projects/eternart/eternart1.png",
    type: "Company Project",
    techStack: [
      "Nextjs",
      "Zustand",
      "Tailwind CSS",
      "MongoDB",
      "Redux",
      "Nodejs",
      "Expressjs",
      "JWT",
    ],
    link: "https://www.ignant.com/2023/10/28/capturing-balis-many-faces-zissou-documents-the-sacred-and-the-mundane-of-a-fragile-island/",
    color: "#2F3437",
    text: "#B3FFCB",
    images: [
      "/projects/eternart/eternart1.png",
      "/projects/eternart/eternart2.png",
      "/projects/eternart/eternart3.png",
      "/projects/eternart/eternart4.png",
    ],
  },
  {
    title: "Refermeet",
    description:
      "A Platform for job seekers and referrers to connect. Job seekers can create profiles, search for jobs, and request referrals. Referrers can view job seekers' profiles, refer them to jobs, and earn rewards.",
    src: "/projects/refermeet/rm1.png",
    type: "Company Project",
    techStack: [
      "Nextjs",
      "TypeScript",
      "Socket.io",
      "Nodemailer",
      "Tailwind CSS",
      "MongoDB",
      "React Query",
      "Nodejs",
      "Expressjs",
      "JWT",
      "Google OAuth",
    ],
    link: "https://www.ignant.com/2023/10/28/capturing-balis-many-faces-zissou-documents-the-sacred-and-the-mundane-of-a-fragile-island/",
    color: "#2F3437",
    text: "#B3FFCB",
    images: [
      "/projects/refermeet/rm1.png",
      "/projects/refermeet/rm2.png",
      "/projects/refermeet/rm3.png",
      "/projects/refermeet/rm4.png",
      "/projects/refermeet/rm5.png",
    ],
  },
  {
    title: "Droomplanet",
    description:
      "A platform for kids where they can buy various programs, listen to different kinds of stories, buy products, read blogs. This platform is for kids to learn and enjoy.",
    src: "/projects/droomplanet/dp1.png",
    type: "Company Project",
    techStack: [
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "MongoDB",
      "React Query",
      "Nodejs",
      "Expressjs",
      "JWT",
      "Google OAuth",
      "Razorpay",
    ],
    link: "https://www.ignant.com/2023/10/28/capturing-balis-many-faces-zissou-documents-the-sacred-and-the-mundane-of-a-fragile-island/",
    color: "#2F3437",
    text: "#B3FFCB",
    images: [
      "/projects/droomplanet/dp1.png",
      "/projects/droomplanet/dp2.png",
      "/projects/droomplanet/dp3.png",
      "/projects/droomplanet/dp4.png",
      "/projects/droomplanet/dp5.png",
    ],
  },
  {
    title: "Mani",
    description:
      "An Ecommerce platform for selling special tshirts, bottoms, and accessories. The platform allows users to browse products, add them to their cart, and purchase them. The platform also allows users to create accounts, view their order history, and manage their account settings.",
    src: "/projects/mani/mani1.png",
    type: "Company Project",
    techStack: [
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "MongoDB",
      "Zustand",
      "Nodejs",
      "Expressjs",
      "JWT",
      "Google OAuth",
      "Razorpay",
    ],
    link: "https://www.ignant.com/2023/10/28/capturing-balis-many-faces-zissou-documents-the-sacred-and-the-mundane-of-a-fragile-island/",
    color: "#2F3437",
    text: "#B3FFCB",
    images: [
      "/projects/mani/mani1.png",
      "/projects/mani/mani2.png",
      "/projects/mani/mani3.png",
      "/projects/mani/mani4.png",
    ],
  },
];

export const links = [
  {
    name: "projects",
    href: "/projects",
  },
  {
    name: "about",
    href: "/about",
  },
  {
    name: "notes",
    href: "/",
  },
  {
    name: "contact",
    href: "/contact",
  },
];
